### ISSUE TITLE
`go!` macro allows its arguments to do `unsafe` operations.

### ISSUE THREAD

**Issue by SkiFire13** [Xudong-Huang/may#105]
The `go!` macro expands the arguments received inside an `unsafe` block, which gives them the ability to do `unsafe` operations even though the user of the macro never used the `unsafe` token. For example the following compiles and immediately segfaults:

```rs
fn main() {
    may::go!(std::ptr::read(0 as *const may::coroutine::Builder), || ());
}
```

The issue is also present for the macro version that takes in a `cqueue`.

A possible solution would be assigning `$builder`, `$cqueue` and `$token` to local variables outside the `unsafe` block.

**Comment by Xudong-Huang** [comment]
this is fix in 0.3.43 release
