### ISSUE TITLE
Unsound problems in `may_queue` crate

### ISSUE THREAD

**Issue by safe4u** [Xudong-Huang/may#110]
Hi, thanks for your contribution to this great coroutine library.

However, we have found lots of unsound problems in the util crate `may_queue`.
For example, the [`set`](https://github.com/Xudong-Huang/may/blob/master/may_queue/src/mpsc.rs#L69) and [`get`](https://github.com/Xudong-Huang/may/blob/master/may_queue/src/mpsc.rs#L91) set and get the data without boundary checking for performance consideration.
These functions are actually unsafe since they ask the caller to guarantee the `index` is in-bound and the compiler fails to check this.

It is certainly ok to mark the unsafe functions as safe and use them with care in 'may'.
But considering the crate `may_queue` is available in [crates.io](https://crates.io/) and these functions are public, we think it's still necessary to make these functions more sound.

## Suggestions
Here are some action choices we suggested:
1. Mark these functions as 'unsafe' which would lead to large code changes.
2. (recommended) Add `assert!` or at least `debug_assert!` macros to validate that the `index` is in-bound.

**Comment by Xudong-Huang** [comment]
just release may_queue 0.1.23 to address this issue
