### ISSUE TITLE
support Unix-specific networking functionality

### ISSUE THREAD

**Issue by Xudong-Huang** [Xudong-Huang/may#17]
ref `std::os::unix::net`

**Comment by Xudong-Huang** [comment]
there is a good ref that discuss named pipes and unix socket
https://github.com/dotnet/corefx/issues/1849

but our first goal is to make a compatible layer for `libstd`

**Comment by antoyo** [comment]
I'll probably not be ready next week, though.
I still have a lot of work to do to switch to `may` in `relm`.

**Comment by Xudong-Huang** [comment]
Ok, I will do the work as soon as possible. I think it's not too complicated. 😃

**Comment by Xudong-Huang** [comment]
@antoyo 
I think this feature is done 🎉

**Comment by antoyo** [comment]
Ok, thank you.
I'm not ready to use this yet, though.
