### ISSUE TITLE
bounded mpmc?

### ISSUE THREAD

**Issue by jedisct1** [Xudong-Huang/may#2]
Hi,

And congrats for May. This is definitely a game changer, that makes it a real joy to do async I/O in Rust.

Is there currently a way to have a bounded mpmc queue? I can use a shared atomic counter, but I was wondering if there was already something available, or if you were planning to implement it.

Cheers!

**Comment by Xudong-Huang** [comment]
Thanks!

There is not a bounded mpmc queue now. and the mpsc queue is also unbounded . But it's easily to implement a bounded mpmc queue with the help of a semaphore.

actually the `May` unbounded mpmc queue is implemented via a semaphore too.

I think it's better to put these special requirement into another library that depend on `May`.

**Comment by jedisct1** [comment]
That makes sense.

Thanks a lot!
