### ISSUE TITLE
Generic Wrapper Type that can be used in coroutine context

### ISSUE THREAD

**Issue by Xudong-Huang** [Xudong-Huang/may#22]
any type that can be converted to the raw fd/handle could be wrapped in a **generic wrapper type** that would automatically have the non-blocking style `Read/Write` in coroutine context.

**Comment by alanhoff** [comment]
Does that means async file handling? It would be awesome!

**Comment by Xudong-Huang** [comment]
I remember that linux doesn't support epoll for normal file access. I create this issue to make things like pipes that used as stdio can be non-blocking in coroutine context.

**Comment by Xudong-Huang** [comment]
windows anonymous pipe doesn't support overlappend read/write, named pipe supports event trigger through IOCP but can't set nonblocking via ioctl. seems that the logic need to refine on windows that only using overlappend read/write. we can't using the nonblocking read/write to try to detect if there is any data already.

**Comment by Xudong-Huang** [comment]
For windows handle type we can only use the `ReadFile`, while the socket type use `WASRecv` API
need to change that accordingly

**Comment by Xudong-Huang** [comment]
MacOs failed to add the pipe fd to the event loop if the other side is closed, we will got a libc::EPIPE error.

**Comment by Xudong-Huang** [comment]
I think this feature is done. But still need better docs and examples

**Comment by alanhoff** [comment]
I can help you with that. Would you mind providing a simple `hello world` usage example?

**Comment by Xudong-Huang** [comment]
oh, thanks! the most obvious example is in [may_process](https://github.com/Xudong-Huang/may_process/blob/master/src/lib.rs)

But I didn't test for the regular file access. I think it would fail to register the event-loop.  A good example would be reading the stdin within a coroutine, but I have no time to stress that now.

```rust
pub fn wait_with_output(mut self) -> io::Result<Output> {
        use may::io::CoIo;

        // first create the io object
        // if the remote pipe is closed, MacOs would return libc::EPIPE
        // when register the fd to the event loop
        macro_rules! async_read_data {
            ($io: expr) => ({
                let mut output = Vec::new();
                match CoIo::new($io) {
                    Ok(mut o) => o.read_to_end(&mut output)?,
                    Err(e) => {
                        // if failed to create CoIo then use default
                        let mut out = e.into_data();
                        out.read_to_end(&mut output)?
                    }
                };
                output
            })
        }

        let status = self.wait()?;

        let stdout = match self.inner.child.stdout.take() {
            Some(o) => async_read_data!(o),
            None => Vec::new(),
        };

        let stderr = match self.inner.child.stderr.take() {
            Some(o) => async_read_data!(o),
            None => Vec::new(),
        };

        Ok(Output {
            status,
            stdout,
            stderr,
        })
    }
```
