### ISSUE TITLE
Is it possible to have coroutine callback not implementing Sync?

### ISSUE THREAD

**Issue by antoyo** [Xudong-Huang/may#26]
Hi.
In my quest to use `may` in `relm`, I've stumbled on the issue that `may` coroutines require both `Send` and `Sync`.
My issue has to do with the fact that `gtk` widgets does not implement these traits, but I think it could workaround this fact by using [`send-cell`](https://github.com/sdroege/send-cell) and executing gtk-related code in the main thread with `MainContext::invoke()` if only the `Send` trait was required.
So, my question is: why is `Sync` required?
Is it because a coroutine can be executed in different threads?
If it is the case, would it be possible to have a coroutine bound to a thread that only require `Send` or a coroutine that `Send` its state to a new thread when it's scheduled to run on a new thread (assuming it is sound)?
(Maybe [this](https://github.com/Xudong-Huang/may/issues/9) can help?)
Thanks.

**Comment by Xudong-Huang** [comment]
this is the `spawn` API
```rust
pub unsafe fn spawn<F, T>(f: F) -> JoinHandle<T>
where
    F: FnOnce() -> T + Send + 'static,
    T: Send + 'static,
{
    ......
}
```
There is no `Sync` requirement for the passed in closure. I think you are trying to move a ref into the closure. A ref is `Send` only when it is `Sync`.

**Comment by antoyo** [comment]
You're right, I'm using a reference.
Thank you.
