### ISSUE TITLE
yield type mismatch error detected

### ISSUE THREAD

**Issue by antoyo** [Xudong-Huang/may#33]
Hi.
I'm currently in the process to port my `relm` crate from `tokio` to `may` (see [this branch](https://github.com/antoyo/relm/tree/feature/may)) and I have an issue with the [`http` example](https://github.com/antoyo/relm/blob/feature/may/examples/http.rs) which is based on [the `may` version of hyper](https://github.com/rust-may/hyper).
The code panic around [here](https://github.com/antoyo/relm/blob/feature/may/examples/http.rs#L115) saying the following error:
```
yield type mismatch error detected, expected type: may::coroutine_impl::EventSubscriber
thread '<unnamed>' panicked at 'Box<Any>'
```
It seems to come from the `coroutine` crate, but I'm not sure why it happens.
Thanks for your help.

**Comment by Xudong-Huang** [comment]
It's likely that you are using different may versions
from hyper, it uses `may = { git = "https://github.com/Xudong-Huang/may.git" }`
but from your toml: `may = "^0.2.0" `
different may version can't coexist, event the same type has different `TypeId` so the panic triggers.

And I never test may version hyper client, but it should be work.

And I can't setup a proper linux box for `relm`, when I run the example, i got following errors
```sh
$ cargo run --example=http
warning: unused manifest key: metadata
    Finished dev [unoptimized + debuginfo] target(s) in 3.62 secs
     Running `/home/ubuntu/Project/rust/relm/target/debug/examples/http`

(.:8530): Gtk-CRITICAL **: _gtk_style_animation_is_static: assertion 'GTK_IS_STYLE_ANIMATION (animation)' failed
[1]    8530 segmentation fault (core dumped)  cargo run --example=http
cargo run --example=http  1.02s user 0.92s system 10% cpu 17.640 total
```
P.S.
Hyper is not optimized for coroutine usage. Maybe you can look at https://github.com/rust-may/may_http.

**Comment by antoyo** [comment]
Ok, it works if I use the `git` version.
Thank you.

(I knew about `may-http` but could it didn't supported the client yesterday.)
