### ISSUE TITLE
Update may-minihttp implementation of TechEmpower benchmark to use serde_derive

### ISSUE THREAD

**Issue by dtolnay** [Xudong-Huang/may#43]
[This line](https://github.com/TechEmpower/FrameworkBenchmarks/blob/0b2750e70b0fb12eec57a6c07db4022092215d49/frameworks/Rust/may-minihttp/src/main.rs#L21) uses the relatively slow serde_json::Value and allocates two BTreeMap nodes and two Strings.

I used the following microbenchmark to compare `json!` vs serde_derive as used by the hyper and tokio-minihttp implementations. On my machine:

```
test bench_derive     ... bench:          59 ns/iter (+/- 5)
test bench_json_value ... bench:         254 ns/iter (+/- 2)
```

This means you are wasting (254 ns/response - 59 ns/response) * 1,148,424 responses/second = 0.224 CPU-seconds per second, which seems like an enormous amount to give up.

```rust
#![feature(test)]

#[macro_use]
extern crate serde_derive;

#[macro_use]
extern crate serde_json;

extern crate serde;
extern crate test;

use test::Bencher;

#[bench]
fn bench_derive(b: &mut Bencher) {
    #[derive(Serialize)]
    struct Message<'a> {
        message: &'a str,
    }

    b.iter(|| {
        serde_json::to_vec(&Message { message: "Hello, World!" }).unwrap();
    });
}

#[bench]
fn bench_json_value(b: &mut Bencher) {
    b.iter(|| {
        serde_json::to_vec(&json!({"message": "Hello, World!"})).unwrap();
    });
}
```

**Comment by Xudong-Huang** [comment]
wow, great catch! thanks!

**Comment by dtolnay** [comment]
Fixed in https://github.com/TechEmpower/FrameworkBenchmarks/pull/3903. Hopefully we see a nice bump for may-minihttp in the next round.
