### ISSUE TITLE
Resolve cast_ref_to_mut Clippy warning

### ISSUE THREAD

**Issue by xfix** [Xudong-Huang/may#48]
I have noticed you have disabled `cast_ref_to_mut` Clippy error. I checked the code, and I found nonsensical code like the following:

```rust
// prevent release version wrong optimization!! use a volatile read
let push_index = unsafe { std::ptr::read_volatile(&self.push_index) };
```

This isn't wrong optimization, this is undefined behaviour caused by `cast_ref_to_mut` violation.

[Volatile is 100% wrong when dealing with thread safety](https://doc.rust-lang.org/std/ptr/fn.read_volatile.html#safety). Please consider migrating to atomic types specifically (atomic types like `AtomicPtr` are inner mutability types by the way). If you are concerned about performance, `Ordering::Relaxed` is pretty much free (other than disabling optimizations that would break this code anyways), so if you don't need atomics at a given point, you can simply use relaxed ordering.

**Comment by Xudong-Huang** [comment]
Thanks for the findings. I think I used to have atomic pointers before, but I found the performance is not as good as the volatile read. The pop operation only allowed one thread access at a time, so I think the volatile read is enough here.

**Comment by xfix** [comment]
Huh?

```
use std::sync::atomic::{AtomicPtr, Ordering};

pub fn read_atomic(x: &AtomicPtr<i32>) -> *mut i32 {
    x.load(Ordering::Relaxed)
}

pub fn write_atomic(x: &AtomicPtr<i32>, v: *mut i32) {
    x.store(v, Ordering::Relaxed)
}
```

Gives me this:

```
example::read_atomic:
        mov     rax, qword ptr [rdi]
        ret

example::write_atomic:
        mov     qword ptr [rdi], rsi
        ret
```

Note that it's using `mov`, not `xchg`. I'm comparing x86_64 here, as likely this code was only tested on x86_64 - it just doesn't look like a volatile write like this could work on other platforms like ARM.

**Comment by Xudong-Huang** [comment]
Thanks for this info, I will fix it in next release.
