### ISSUE TITLE
Use crossbeam dequeue for task scheduling

### ISSUE THREAD

**Issue by Xudong-Huang** [Xudong-Huang/may#49]
ref https://docs.rs/crossbeam/0.7.1/crossbeam/deque/index.html

**Comment by stjepang** [comment]
Hi! I'm considering releasing version 1.0 for `crossbeam-deque` sometime this year so I wonder if you have any feedback to share? Is there anything missing in the crate or something you wish was designed differently? How's the crate working for `may`?

**Comment by Xudong-Huang** [comment]
It's great, fast and stable. I'm glad to hear that it's going to 1.0. Thanks!
