### ISSUE TITLE
UB in config

### ISSUE THREAD

**Issue by vorner** [Xudong-Huang/may#5]
I looked into the code a bit and this is what I found:

https://github.com/Xudong-Huang/may/blob/master/src/config.rs#L25
```rust
    pub fn set_io_workers(&self, workers: usize) -> &Self {
        info!("set io workers={:?}", workers);
        unsafe {
            IO_WORKERS = workers;
        }
        self
    }
```

`IO_WORKERS` is defined as `static mut WORKERS: usize = 2;`. There's *nothing* preventing the user of the library from calling this from multiple threads, which is by definition a data race (unsynchronized access from multiple threads, at least one of them is write), which is undefined behaviour:
https://doc.rust-lang.org/reference/behavior-considered-undefined.html

The function is not marked as unsafe. This means the user of the library is able to invoke UB without using any UB on his side, which is what Rust should be preventing.

Please use appropriate tools for synchronisation (either mutex or atomis).

**Comment by Xudong-Huang** [comment]
thanks for reporting this. I expect config happened at the very beginning of the program, just like the log initialization. I will update the doc and simply panics if the scheduler is already started.

**Comment by vorner** [comment]
That's not the point. With Rust you shouldn't just „expect“. Big selling point of Rust is to *make sure* it isn't possible.

The user can invoke UB by running the config methods even before the scheduler starts from multiple threads. Yes, you can ask why he would do that, but a lot can happen by accident.

The unsafe there simply doesn't bring you anything. Why ever risk/consider unsafe, when using a `std::sync::AtomicUsize` is perfectly fine option?

**Comment by Xudong-Huang** [comment]
@vorner  2101c6d should fix the issue.
want to know if you have any comments about the update
