### ISSUE TITLE
Is there any reason to use the may::net API instead of the std::net?

### ISSUE THREAD

**Issue by Gymmasssorla** [Xudong-Huang/may#55]
I guess it has some performance benefits, but it's still a kind of mystery for me. So could you explain because of what may::net is faster than the standard std::net?

**Comment by Xudong-Huang** [comment]
Well, it only has effect when you use the may:net APIs in coroutine context. If you are using the APIs in normal thread context, it actually has some extra overhead check compared with the std APIs. The benefit is   from async scheduling in coroutine context,  it will not block any thread execution.

**Comment by Gymmasssorla** [comment]
Thank you, now it's clear for me :)
