### ISSUE TITLE
License consistency

### ISSUE THREAD

**Issue by GallagherCommaJack** [Xudong-Huang/may#56]
Currently may depends on may_queue, which is LGPL, but is itself licensed under MIT/Apache. This is against the terms of the LGPL. Since you're also the author of may_queue, can you replace the license there with MIT/Apache?

Alternately, you could make all of the may libraries LGPL, or another GPL-compatible license.

**Comment by Xudong-Huang** [comment]
Thanks! Apparently it's a mistake.
