### ISSUE TITLE
How to cancel a coroutine?

### ISSUE THREAD

**Issue by Gymmasssorla** [Xudong-Huang/may#59]
It seems that this crate provides the ability to cancel coroutines, but I can't resolve how to do it. What is the general syntax for coroutine cancellation?

**Comment by Xudong-Huang** [comment]
Yes, you can use the `cancel` method when you have a coroutine handle. There is no API to cancel a whole scoped coroutines.

**Comment by Xudong-Huang** [comment]
you could use the `select!` macro with a timeout branch. if the timeout happens, it will cancel all the other branches. and in the select macro, you can use local ref too.

**Comment by Gymmasssorla** [comment]
Could you please provide an example with a `select!` macro with a timeout branch?
