### ISSUE TITLE
Is it OK to use std::sync::Arc in coroutine-context?

### ISSUE THREAD

**Issue by Gymmasssorla** [Xudong-Huang/may#64]
I want to share immutable data between several coroutines. Is it OK to use the standard `Arc` or MAY has its own structure?

**Comment by Xudong-Huang** [comment]
yes, you should always use Arc in coroutines to share memory. Multi coroutine programming is essentially multi thread programming

**Comment by Gymmasssorla** [comment]
Thanks you
