### ISSUE TITLE
Why is the library called `may`?

### ISSUE THREAD

**Issue by abbychau** [Xudong-Huang/may#65]
I and my colleague made a few guesses, that this project starts in May. Or the name of the cat, girlfriend, mother, father, grandma, grandpa.... is called may?

**Comment by Xudong-Huang** [comment]
Ah, my daughter born in may, and her nickname is 五月, which means may. 😄

**Comment by abbychau** [comment]
I see~ She must be a cute baby.

I enjoyed using `may`, as a library. Thank you.
