### ISSUE TITLE
Not all coroutines get executed

### ISSUE THREAD

**Issue by Trivernis** [Xudong-Huang/may#77]
I wanted to use the `go!` coroutines to calculate primes with multithreading after I found out that the std::thread is slower than the go coroutines. I replaced the call `thread::spawn` with `go!` and added the line `may::config().set_workers(num_cpus::get());`. The coroutines get started in a for loop that counts to the number of cpus so that it starts as many threads as cores. Now my problem is that the number of coroutines that are actually running varies, basically every time I start the program its between 3 and 6 (I have 8 cores). My question is If I'm missing something.
([link to the repo](https://github.com/parallel-programming-hwr/rust-primes)).

**Comment by Xudong-Huang** [comment]
It's correct for that each worker thread steal a batch of works one time, which means it will cache several ready coroutines in it's local work queue. if the work is too short, other thread has less opportunity to steal them. I suggest you create more work load to  make the cpu full.

**Comment by Trivernis** [comment]
Hmm, but shouldn't 8 coroutines (for 8 cores) that calculate prime numbers in an infinity loop generate 100% cpu load?

**Comment by Xudong-Huang** [comment]
I didn't aware it was finite loop. Thanks for the report, I will check the scheduler, seems there is something wrong.

**Comment by Xudong-Huang** [comment]
Test with the latest code. I think this problem is resolved. I will make a new release to fix that.

**Comment by Trivernis** [comment]
Okay, thank you :smiley:
