### ISSUE TITLE
Question for how to get the Coroutines Id?What should I do for doing a Heavy IO？just like request an http,or read write file?

### ISSUE THREAD

**Issue by zhuxiujia** [Xudong-Huang/may#79]
* how to get the Coroutines Id?
 (some times a Database transactions runing and bind in  a Coroutine,we use a threadLocal to save it. i 'cant find this api in may )
* What should I do for doing other Heavy IO？
just like send an http request ,or read write file,but the example haven't .
* Finally, may  can work with Tokio Together?

**Comment by Xudong-Huang** [comment]
When spawn coroutines, you get a handle for each coroutine. And you can use the `JoinHandle::coroutine()` API to get the underlining coroutine instance. This is something like the coroutine Id. If you are trying to do something map control, you can ref [co_waiter](https://github.com/Xudong-Huang/co_waiter) project.

Heavy IO is generated from the client. You should ref to the echo_client implementation in example.

May can work with tokio. just like thread can work with futures. But notice that you have two runtimes in your system if you are tring to do that.

**Comment by zhuxiujia** [comment]
> When spawn coroutines, you get a handle for each coroutine. And you can use the `JoinHandle::coroutine()` API to get the underlining coroutine instance. This is something like the coroutine Id. If you are trying to do something map control, you can ref [co_waiter](https://github.com/Xudong-Huang/co_waiter) project.
> 
> Heavy IO is generated from the client. You should ref to the echo_client implementation in example.
> 
> May can work with tokio. just like thread can work with futures. But notice that you have two runtimes in your system if you are tring to do that.

如果 我要发起一个io任务，例如发起http请求，是不是用
```rust
go!(move || { 
//do io job
})
```
宏包装一下就行？

**Comment by Xudong-Huang** [comment]
yes, you are right.

**Comment by zhuxiujia** [comment]
> yes, you are right.

That looks a lot better than the future. Cool
