### ISSUE TITLE
Is it safe to use `may::sync::Mutex` in non-coroutine context?

### ISSUE THREAD

**Issue by playXE** [Xudong-Huang/may#82]
I'm developing programming language runtime and I have to access some of values stored in coroutines to do concurrent marking and I need some synchronization, but GC threads is not coroutines, instead it just two or four native threads.

**Comment by Xudong-Huang** [comment]
Yes, it's safe. All the APIs could be used in non-coroutine context

**Comment by playXE** [comment]
Thanks for help!
