### ISSUE TITLE
Feature request: Stop-the-world mechanism

### ISSUE THREAD

**Issue by playXE** [Xudong-Huang/may#83]
It would be nice to see some API to stop execution of *all* coroutines and then resuming them.
```rust
may::park_all();
/* do something */
may::unpark_all();
```
`park_all` and `unpark_all` could be executed in both non-coroutine and coroutine contexts.

## Implementation
It's possible to have `static PARK_ALL: AtomicBool` and at yeach yield to scheduler context check `PARK_ALL`.  But STW mechanism might also require to store coroutine or context that requested STW to resume this context.

**Comment by Xudong-Huang** [comment]
Doing the check in the scheduler is better. But this will hurt the overall performance. I don't think will support this feature in the master branch.
