### ISSUE TITLE
Any plans supporting ARM on linux?

### ISSUE THREAD

**Issue by mjarkk** [Xudong-Huang/may#84]
In the readme the following is stated:  
> - Both x86_64 GNU/Linux, x86_64 Windows, x86_64 Mac OS are supported.

I love this library and have used it for a few project already but now i want to use it in a Raspberry Pi project but it seems like that's impossible 😢.  
Are there any plans for supporting ARM architecture in the further?

**Comment by Xudong-Huang** [comment]
with 0.3.19 we add support for aarch64 linux platforms

**Comment by mjarkk** [comment]
Great!
Sadly by now i've found something else to use but hey still thanks always nice to have arm support in libraries.
