### ISSUE TITLE
question: way not generator-rs   Stack resizes automatically?

### ISSUE THREAD

**Issue by zhuxiujia** [Xudong-Huang/may#87]
way not generator-rs   Stack resizes automatically?

* There is an overflow risk for a fixed size stack.Too much memory waste, too small easy overflow
* Can we use Vec instead of stack to achieve automatic scaling。 Or  generator-rs support raw api  Stack resizes automatically
* The Go language pauses on the stack and switches to other coroutines until the stack scales and then cuts back

**Comment by Xudong-Huang** [comment]
The problem here is that the stack can't change it's address, resize or realloc the memory would change the stack address, and this would break every thing. Currently I don't know how to generate stack independent code in rust.

**Comment by zhuxiujia** [comment]
> The problem here is that the stack can't change it's address, resize or realloc the memory would change the stack address, and this would break every thing. Currently I don't know how to generate stack independent code in rust.

Whether the required stack space size can be calculated at compile time？

**Comment by MSE99** [comment]
> The problem here is that the stack can't change it's address, resize or realloc the memory would change the stack address, and this would break every thing. Currently I don't know how to generate stack independent code in rust.

I'm not really experienced in this topic, but i was wondering if it would it still break everything if for example coroutine A doesn't have any reference to any object allocated on the stack of coroutine B, in languages like erlang coroutines do not share memory by default and memory management (garbage collection, stack resizing) happens at the coroutine level rather than globally.

**Comment by zhuxiujia** [comment]
> > The problem here is that the stack can't change it's address, resize or realloc the memory would change the stack address, and this would break every thing. Currently I don't know how to generate stack independent code in rust.
> 
> I'm not really experienced in this topic, but i was wondering if it would it still break everything if for example coroutine A doesn't have any reference to any object allocated on the stack of coroutine B, in languages like erlang coroutines do not share memory by default and memory management (garbage collection, stack resizing) happens at the coroutine level rather than globally.
The expansion and contraction of coroutine memory are generally achieved by copying stack data onto a new stack,

The expansion and contraction of coroutine memory are generally achieved by copying stack data onto a new stack,

For example, the function of the coroutine internally initializes let arr=[0u8, 1u8, 2u8];

And the variable let b=&arr [1];

After the stack space shrinks, variable b becomes invalid, which will destroy everything
