### ISSUE TITLE
Examples don't compile

### ISSUE THREAD

**Issue by InterestingBrainPoops** [Xudong-Huang/may#89]
I tried compiling the examples on Windows 10, and I'm getting the error `E0658`, which has to do with the const generics used in one of your dependencies. I tried switching to nightly, but that's giving me a linker error (probably unrelated). I don't see anywhere in your README that may needs nightly to compile, so I'm quite confused. Thanks in advance.

**Comment by Xudong-Huang** [comment]
we need stable rust 1.51, you can see from the travis log https://travis-ci.org/github/Xudong-Huang/may/jobs/765476043
both stable and nightly are supported with latest rust tool chain release

**Comment by InterestingBrainPoops** [comment]
Ah ok, thank you for the info. I updated my rust version to 1.51, and I found that the quicksort example works as intended, but the prime example doesnt compile on stable due to the fact that it uses a nightly only feature for testing. I deleted the tests, and it worked fine. I'll submit a PR to the prime example so that it uses the stable testing framework!
