### ISSUE TITLE
about performace.md The description is unfair

### ISSUE THREAD

**Issue by zhuxiujia** [Xudong-Huang/may#90]
tokio's example default features is enable ``` "rt-multi-thread"  ```
We know that when this is enabled, task stealing occurs inside Tokio and this feature severely affects performance (at least twice as slow). 
*  I think a comparison should be made with Actix-Web(It is  based on Tokio), which uses a separate runtime for each thread.
* Another option is that ```may``` and ```Tokio``` both limit the number of threads and ensure that Tokio uses a single-threaded runtime

**Comment by Xudong-Huang** [comment]
It's very old comparation. you can just ignore that. the [TFB](https://tfb-status.techempower.com/)should be a good place to check.
`May` is using a scheduler which is something like tokio's `"rt-multi-thread"`

**Comment by zhuxiujia** [comment]
> It's very old comparation. you can just ignore that. the [TFB](https://tfb-status.techempower.com/)should be a good place to check. `May` is using a scheduler which is something like tokio's `"rt-multi-thread"`


Can ```may```  provide type to use a separate runtime for each thread? just like  actix. In some scenarios, cross-thread stealing is not necessary.


A similar crates already exists
you can see  [monoio](https://mp.weixin.qq.com/s/DwgMGxmIt_FY-BPg3DfYkA)

**Comment by Xudong-Huang** [comment]
The design was only considering the work stealing pattern. But implement a non work stealing scheduler is possible and may result a huge change of the project. I have no plan to do that.
